# netlify.toml - Netlify 서버를 위한 규칙 파일

# 1. API 요청을 위한 규칙
# /wp-json/ 으로 시작하는 모든 요청을 실제 API 서버로 전달합니다.
[[redirects]]
  from = "/wp-json/*"
  to = "https://api.asura.design/wp-json/:splat"
  status = 200 # 200은 '재작성(Rewrite)'을 의미하며, URL이 바뀌지 않습니다.

# 2. 폰트, 이미지 등 미디어 파일을 위한 규칙
# /wp-content/ 로 시작하는 모든 요청을 실제 워드프레스 서버로 전달합니다.
[[redirects]]
  from = "/wp-content/*"
  to = "https://api.asura.design/wp-content/:splat"
  status = 200