# netlify.toml - 최종 버전

# API 및 정적 파일 프록시 규칙 (가장 먼저 처리되어야 함)
[[redirects]]
  from = "/wp-json/*"
  to = "https://api.asura.design/wp-json/:splat"
  status = 200

[[redirects]]
  from = "/wp-content/*"
  to = "https://api.asura.design/wp-content/:splat"
  status = 200

# SPA 라우팅을 위한 'Catch-all' 규칙 (가장 마지막에 와야 함)
# 위 규칙에 해당하지 않는 모든 요청은 index.html로 보냅니다.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200